name: TG-Core
version: '${project.version}'
main: net.trustgames.core.Core
description: Core plugin for TrustGames.net
api-version: '1.19'
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true

    MiniPlaceholders:
      load: BEFORE
      required: true
      join-classpath: true

    MiniPlaceholders-Player-Expansion:
      load: BEFORE
      required: true
      join-classpath: true

    MiniPlaceholders-LuckPerms-Expansion:
      load: BEFORE
      required: true
      join-classpath: true

    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true

