name: TG-Core
version: '${project.version}'
main: net.trustgames.core.Core
description: Core plugin for TrustGames.net
api-version: '1.19'
dependencies:
  - name: LuckPerms
    required: true
    bootstrap: false

  - name: MiniPlaceholders
    required: true
    bootstrap: false

  - name: player-expansion-paper
    required: true
    bootstrap: false

  - name: LuckPerms-Expansion
    required: true
    bootstrap: false

