load: POSTWORLD
depend:
  - LuckPerms
  - ProtocolLib
softdepend:
  - PlaceholderAPI
name: Core
version: '${project.version}'
main: net.trustgames.core.Core
api-version: 1.19
authors: [ Wega ]
description: Core plugin for TrustGames.net
website: www.trustgames.net
commands:
  discord:
    description: Get the discord server url
  website:
    description: Get the website url
    aliases:
      - web
  store:
    description: Get the store url
    aliases:
      - vip
      - benefits
      - buy
      - shop


