load: POSTWORLD
depend:
  - LuckPerms
softdepend:
  - PlayerNPC
name: Core
version: '${project.version}'
main: net.trustgames.core.Core
api-version: 1.19
authors: [ Wega ]
description: Core plugin for TrustGames.net
website: www.trustgames.net
commands:



