load: POSTWORLD
depend:
  - LuckPerms
  - ProtocolLib
softdepend:
  - PlaceholderAPI
name: Core
version: '${project.version}'
main: net.trustgames.core.Core
api-version: 1.19
authors: [ Wega ]
description: Core plugin for TrustGames.net
website: www.trustgames.net
commands:
  discord:
    description: Get the discord server url
  website:
    description: Get the website url
    aliases:
      - web
  store:
    description: Get the store url
    aliases:
      - vip
      - benefits
      - buy
      - shop

  activity:
    description: Get the player's activity by his name or UUID from the database
    permission: core.staff
  activity-id:
    description: Get the activity by it's ID from the database
    permission: core.staff

  kills:
    description: Get personal or targets coins
    aliases:
      - deaths
      - games
      - playtime
      - xp
      - level
      - gems
      - rubies



