depend:
  - LuckPerms
  - ProtocolLib
softdepend:
  - PlaceholderAPI
name: Core
version: '${project.version}'
main: net.trustgames.core.Core
api-version: 1.19
authors: [ Wega ]
description: Core plugin for TrustGames.net
website: www.trustgames.net
commands:
  discord:
    description: Get the discord server url
    aliases:
      - dsc
  website:
    description: Get the website url
    aliases:
      - web
  store:
    description: Get the store url
    aliases:
      - vip
      - benefits
      - buy
      - shop
  activity:
    usage: /activity <Player/UUID>
    description: Get the player's activity by his name or UUID from the database
    permission: core.staff
    aliases:
       - activ
       - act
  activity-id:
    usage: /activity-id <ID>
    description: Get the activity by it's ID from the database
    permission: core.staff
    aliases:
      - activ-id
      - act-id
      - activityid


